on: push
name: Reproducibility Check

jobs:
  render:
    name: execute notebook
    runs-on: ${{ (github.repository_owner == 'espm-157' && github.event.repository.private) && 'arc-runner-espm157' || 'ubuntu-latest' }}
    container: ${{ (github.repository_owner == 'espm-157' && github.event.repository.private) && 'rocker/ml' || '' }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: '3.11.9' 
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: test
        run: |
             echo "machine urs.earthdata.nasa.gov login earthaccess password EDL_test1" > ~/.netrc
             rm -f github-login.ipynb # exclude login from testing
             pytest --nbval-lax *.ipynb
#      - name: render
#        run: myst build climate.md --pdf
